constructor/constructor.WebSite/Areas/Cabinet/Controllers/SettingsController.cs
using Interfaces.Account;
using Interfaces.Content;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebSite.Areas.Cabinet.Models;
using WebSite.Areas.Cabinet.Models.LandingIntegration;

namespace WebSite.Areas.Cabinet.Controllers
{
    public class SettingsController : CabinetBaseController
    {
        private readonly ILandingService _landingService;
        private readonly ILandingSettingsService _settingService;
        private readonly IUserService _userService;
        public SettingsController(ILandingService landingService, ILandingSettingsService settingService, IUserService userService)
        {
            _landingService = landingService;
            _settingService = settingService;
            _userService = userService;
        }

        // GET: Cabinet/Settings
        public ActionResult Index(string url = "")
        {
            var landing = _landingService.GetByUrl(url);
            if (landing == null)
                return HttpNotFound();
            var landingSettings = new LandingSettingsViewModel();
            landingSettings.Id = landing.Id;
            landingSettings.Url = url;           
            return View(landingSettings);
        }

        public ActionResult Setting(string url = "")
        {
            var landing = _landingService.GetByUrl(url);
            if (landing == null)
                return HttpNotFound();
            var landingSettings = new LandingSettingsViewModel();
            landingSettings.Id = landing.Id;
            landingSettings.Url = url;
            landingSettings.Email = _userService.GetByName(User.Identity.Name).Email;
            landingSettings.IsNotify = _userService.GetByName(User.Identity.Name).IsNotify;
            landingSettings.Phone = _userService.GetByName(User.Identity.Name).Phone;
            ViewBag.LandingUrl = landingSettings.Url;            
            return View(landingSettings);
        }

        public ActionResult Integration(string url = "")
        {
            var landing = _landingService.GetByUrl(url);
            if (landing == null)
                return HttpNotFound();
            var landingSettings = new LandingSettingsViewModel();
            landingSettings.LandingId = landing.Id;
            landingSettings.Url = url;

            var setting = _settingService.GetByLandingId(landing.Id);
            if (setting!=null)
            {
                var settingsModel = JsonConvert.DeserializeObject<LandingSettingsViewModel>(setting.SettingsJson);
                landingSettings = settingsModel;
                landingSettings.Id = setting.Id;
            }
            else
            {
                landingSettings.LandingId = landing.Id;
                landingSettings.Url = landing.Url;
                var jsonString = JsonConvert.SerializeObject(landingSettings);
                var newSetting = _settingService.Add(new DomainModel.Content.LandingSetting()
                {
                    LandingId = landing.Id,
                    SettingsJson = jsonString
                });
                landingSettings.Id = newSetting.Id;
            }
            
            ViewBag.LandingUrl = landingSettings.Url;
            return View(landingSettings);
        }

        public ActionResult MailSettings(string url = "")
        {
            var landing = _landingService.GetByUrl(url);
            if (landing == null)
                return HttpNotFound();
            var landingSettings = new LandingSettingsViewModel();
            landingSettings.Id = landing.Id;
            landingSettings.Url = url;
            landingSettings.Email = landing.Email;
            landingSettings.IsNotify = _userService.GetByName(User.Identity.Name).IsNotify;
            ViewBag.LandingUrl = landingSettings.Url;
            return View(landingSettings);
        }

        [HttpPost]
        public ActionResult MailSettings(string Email, string Url, int LandingId)
        {
            _landingService.SetEmail(Email, LandingId);
            return RedirectToAction("MailSettings", new { url = Url });
        }

        [HttpPost]
        public ActionResult UpdateNotify(bool value)
        {                     
                _userService.UpdateNotify(User.Identity.Name, value); 
                                
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult IntegrationBool(LandingSettingsViewModel model)
        {

            var setting = _settingService.GetById(model.Id);
            if (setting != null)
            {
                var settingsModel = JsonConvert.DeserializeObject<LandingSettingsViewModel>(setting.SettingsJson);
                settingsModel.IsAmocrm = model.IsAmocrm;
                settingsModel.IsSendpulse = model.IsSendpulse;
                settingsModel.IsMailchimp = model.IsMailchimp;
                settingsModel.IsSmsintel = model.IsSmsintel;
                var jsonString = JsonConvert.SerializeObject(settingsModel);
                _settingService.Update(new DomainModel.Content.LandingSetting()
                {
                    Id = model.Id,
                    SettingsJson = jsonString
                });
            }
            return RedirectToAction("Integration", new { url = model.Url });
        }

        [HttpPost]
        public ActionResult IntegrationAmocrm(LandingSettingsViewModel model)
        {

            var setting = _settingService.GetById(model.Id);
            if (setting != null)
            {
                var settingsModel = JsonConvert.DeserializeObject<LandingSettingsViewModel>(setting.SettingsJson);
                settingsModel.AmoCrm = new AmoCrmModel()
                {
                    SubDomain = model.AmoCrm.SubDomain,
                    UserHash = model.AmoCrm.UserHash,
                    UserLogin = model.AmoCrm.UserLogin
                };                
                var jsonString = JsonConvert.SerializeObject(settingsModel);
                _settingService.Update(new DomainModel.Content.LandingSetting()
                {
                    Id = model.Id,
                    SettingsJson = jsonString
                });
            }
            return RedirectToAction("Integration", new { url = model.Url });
        }

        [HttpPost]
        public ActionResult IntegrationGetResponse(LandingSettingsViewModel model)
        {
            var setting = _settingService.GetById(model.Id);
            if (setting != null)
            {
                var settingsModel = JsonConvert.DeserializeObject<LandingSettingsViewModel>(setting.SettingsJson);
                settingsModel.GetResponse = new GetResponse360()
                {
                    Api_key = model.GetResponse.Api_key,
                    Api_url = model.GetResponse.Api_url,
                    CampaignId = model.GetResponse.CampaignId
                };
                var jsonString = JsonConvert.SerializeObject(settingsModel);
                _settingService.Update(new DomainModel.Content.LandingSetting()
                {
                    Id = model.Id,
                    SettingsJson = jsonString
                });
            }
            return RedirectToAction("Integration", new { url = model.Url });
        }

        [HttpPost]
        public ActionResult IntegrationMailchimp(LandingSettingsViewModel model)
        {

            var setting = _settingService.GetById(model.Id);
            if (setting != null)
            {
                var settingsModel = JsonConvert.DeserializeObject<LandingSettingsViewModel>(setting.SettingsJson);
                settingsModel.MailChimp = new MailChimpModel()
                {
                    MailChimpApiKey = model.MailChimp.MailChimpApiKey,
                    ListId = model.MailChimp.ListId
                };
                var jsonString = JsonConvert.SerializeObject(settingsModel);
                _settingService.Update(new DomainModel.Content.LandingSetting()
                {
                    Id = model.Id,
                    SettingsJson = jsonString
                });
            }
            return RedirectToAction("Integration", new { url = model.Url });
        }

        [HttpPost]
        public ActionResult IntegrationSendpulse(LandingSettingsViewModel model)
        {

            var setting = _settingService.GetById(model.Id);
            if (setting != null)
            {
                var settingsModel = JsonConvert.DeserializeObject<LandingSettingsViewModel>(setting.SettingsJson);
                settingsModel.SendPulse = new SendPulseModel()
                {
                    PulseSecret = model.SendPulse.PulseSecret,
                    PulseId = model.SendPulse.PulseId,
                    BookId = model.SendPulse.BookId
                };
                var jsonString = JsonConvert.SerializeObject(settingsModel);
                _settingService.Update(new DomainModel.Content.LandingSetting()
                {
                    Id = model.Id,
                    SettingsJson = jsonString
                });
            }
            return RedirectToAction("Integration", new { url = model.Url });
        }

        [HttpPost]
        public ActionResult IntegrationBitrix(LandingSettingsViewModel model)
        {

            var setting = _settingService.GetById(model.Id);
            if (setting != null)
            {
                var settingsModel = JsonConvert.DeserializeObject<LandingSettingsViewModel>(setting.SettingsJson);
                settingsModel.Bitrix = new Bitrix24Model()
                {
                    ClientId = model.Bitrix.ClientId,
                    ClientSecret = model.Bitrix.ClientSecret                    
                };
                var jsonString = JsonConvert.SerializeObject(settingsModel);

constructor/constructor.WebSite/Areas/Cabinet/Views/Settings/Index.cshtml
@model WebSite.Areas.Cabinet.Models.LandingSettingsViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Cabinet/Views/Shared/_LayoutSettingPanel.cshtml";
}

<h2>настройки</h2>

<div class="form-horizontal">

    <div class="form-group">
        <label class="col-md-3 control-label">Outline Checkboxes</label>
        <div class="col-md-9">
            <div class="mt-checkbox-list">
                <label class="mt-checkbox mt-checkbox-outline">
                    <input type="checkbox"> Checkbox 1
                    <span></span>
                </label>
                <label class="mt-checkbox mt-checkbox-outline">
                    <input type="checkbox"> Checkbox 1
                    <span></span>
                </label>
                <label class="mt-checkbox mt-checkbox-outline mt-checkbox-disabled">
                    <input type="checkbox" disabled=""> Disabled
                    <span></span>
                </label>
            </div>
        </div>
    </div>

</div>

constructor/constructor.WebSite/Areas/Cabinet/Views/Settings/MailSettings.cshtml
@model WebSite.Areas.Cabinet.Models.LandingSettingsViewModel
@{
    ViewBag.Title = "MailSettings";
    Layout = "~/Areas/Cabinet/Views/Shared/_LayoutSettingPanel.cshtml";
}

<div class="row">
    <div class="col-lg-12 col-xs-12 col-sm-12">
        <div class="portlet light ">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject bold uppercase font-dark">Настройки уведомлений</span>                    
                </div>
                <div class="actions">                    
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="#" data-original-title="" title="на полный экран"> </a>
                </div>
            </div>
            <div class="portlet-body form">
                <form role="form" method="post">
                    <div class="form-body">
                        <input type="hidden" name="LandingId" value="@Model.Id" />
                        <input type="hidden" name="Url" value="@ViewBag.LandingUrl" />                       
                        <div class="form-group">
                            <label>Адрес электронной почты</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-envelope"></i>
                                </span>
                                <input type="text" class="form-control" name="Email" value="@Model.Email" placeholder="email">
                            </div>
                        </div>                        
                    </div>
                    <div class="form-actions right1">                        
                        <button type="submit" class="btn red">Сохранить</button>
                    </div>                   
                </form>
            </div>
        </div>
    </div>    
</div>

<div class="row">
    <div class="col-lg-12 col-xs-12 col-sm-12">
        <div class="portlet light ">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject bold uppercase font-dark">Уведомления</span>
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="#" data-original-title="" title="на полный экран"> </a>
                </div>
            </div>
            <div class="portlet-body form">
                <div class="form-group">                    
                    <div class="mt-checkbox-list">
                        <label class="mt-checkbox mt-checkbox-outline">
                            Уведомлять о отправленных формах
                            @Html.CheckBoxFor(_=>_.IsNotify, new { @class = "chkNotify" })                            
                            <span></span>
                        </label>                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('.chkNotify').change(function (e) {
        if ($(e.target).prop('checked')) {
            $.post('@Url.Action("UpdateNotify","Settings")', { value: true }, function () { });
        }
        else {
            $.post('@Url.Action("UpdateNotify","Settings")', { value: false }, function () { });
        }
    });
</script>

constructor/constructor.WebSite/Areas/Cabinet/Views/Settings/Setting.cshtml
@model WebSite.Areas.Cabinet.Models.LandingSettingsViewModel
@{
    ViewBag.Title = "Общие настройки";
    Layout = "~/Areas/Cabinet/Views/Shared/_LayoutSettingPanel.cshtml";
}

<div class="row">
    <div class="col-lg-12 col-xs-12 col-sm-12">
        <div class="portlet light ">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject bold uppercase font-dark">Общие настройки</span>
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="#" data-original-title="" title="на полный экран"> </a>
                </div>
            </div>
            <div class="portlet-body form">
                <form role="form">
                    <div class="form-body">
                        <div class="form-group">
                            <label>Адрес электронной почты</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-envelope"></i>
                                </span>
                                <input type="text" class="form-control" name="Email" readonly value="@Model.Email" placeholder="email">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Телефон</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-envelope"></i>
                                </span>
                                <input type="text" class="form-control" name="Phone" readonly value="@Model.Phone" placeholder="телефон">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>